spring:
  application:
    name: entree-service
#  cloud:
#    client:
#      hostname: localhost

server:
  port: 8081

eureka:
  instance:
#    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

wfd:
  entree:
    order: 2
    type: dinner
    menu:
      - Steak
      - Chicken
      - Fish
