apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
data:
  application.yaml: |+
    spring:
      sleuth:
        sampler:
          percentage: 1.0
      zipkin:
        baseUrl: http://{{ .Values.zipkin.service }}:{{ .Values.zipkin.port }}

    server:
      port: {{ .Values.image.containerPort }}

    eureka:
      client:
        serviceUrl:
           defaultZone: http://{{ .Values.eureka.service }}:{{ .Values.eureka.port }}/eureka/
      instance:
        preferIpAddress: {{ .Values.eureka.preferIpAddress }}

    wfd:
      entree:
        order: 2
        type: dinner
        menu:
          - Steak
          - Chicken
          - Fish

  bootstrap.yaml: |+
    spring:
      cloud:
        config:
          enabled: true
          uri: http://{{ .Values.config.service }}:{{ .Values.config.port }}
